# Generated by Django 4.2.16 on 2024-09-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_specialcare_alter_farrierappt_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialCare',
            new_name='Care',
        ),
    ]
